version: '3'
services:
  balek-guestbook:
    image: "balek-guestbook:release"
    build:
      context: "../.."
      dockerfile: "builds/guestbook/Dockerfile"
    ports:
      - "443:8080"
    volumes:
      - ./conf:/balek/src/balek-server/etc
  mongodb-guestbook:
    image: "balek-guestbook-mongodb:release"
    build: "../docker/mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
      - MONGO_INITDB_DATABASE=balek
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d/
      - ./mongoDB:/data/db