version: '3'
services:
  balek:
    image: "diaplode:release"
    build:
      context: "../.."
      dockerfile: "builds/diaplode/Dockerfile"
    ports:
      - "443:8080"
    volumes:
      - ./conf:/balek/src/balek-server/etc
  mysqld:
    image: "diaplode-mysql:release"
    build: "../../data/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_DATABASE=balek
      - MYSQL_USER=balekAppUser
      - MYSQL_PASSWORD=balekAppPassword
    ports:
        - "3306:3306"
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d/:ro
      - ./mysqlDB:/var/lib/mysql
  mongodb:
    image: "diaplode-mongodb:release"
    build: "../../data/mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
      - MONGO_INITDB_DATABASE=balek
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d/
      - ./mongoDB:/data/db
  openssh:
    image: "balek-openssh:release"
    build: "docker/openssh"
    hostname: balek-openssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
      - PASSWORD_ACCESS=false
      - PUBLIC_KEY_FILE=conf/cert/ssh/id_rsa.pub
      - USER_NAME=diaplode
    volumes:
      - ./config:/config
    ports:
      - 2222:2222
    restart: unless-stopped