FROM  ghcr.io/linuxserver/openssh-server


RUN apk update
RUN apk add openssh-client

#RUN cd /config
#RUN ssh-keygen -q -t rsa -N '' -f /config/id_rsa
#RUN mkdir /config/.ssh
#RUN cp /config/id_rsa.pub /config/.ssh/authorized_keys
