FROM node:20

WORKDIR /balek
COPY ./ /balek


#RUN npm --prefix ./src/balek-modules install ./src/balek-modules
#RUN npm --prefix ./src/balek-modules run build

RUN apt-get update
RUN apt-get install -y default-jre
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    python3-pip \
    python3-dev \
    make \
    g++ \
    gcc \
    libssl-dev \
    git \
    curl

RUN apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libtool autoconf automake
#Next two lines for windows docker hosts, otherwise not needed
RUN apt-get install -y dos2unix
RUN find /balek -type f -print0 | xargs -0 -n 1 -P 4 dos2unix

RUN npm install

run npm install canvas --build-from-source


RUN npm run buildAll
#RUN npm --prefix ./src/balek-modules run buildRelease

#RUN mkdir
#RUN ssh-keygen -q -t rsa -N '' -f /id_rsa
#RUN mkdir ~/.ssh
#RUN cp /id_rsa.pub ~/.ssh/authorized_keys

# Run loadServer.js when the container launches

CMD ["node", "loadServer.js"]




EXPOSE 8080
